# Generated by Django 2.2.19 on 2021-05-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='author',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favor_recipe',
            field=models.ManyToManyField(blank=True, related_name='recipe', to='recipes.FavorRecipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='shoplist',
            field=models.ManyToManyField(blank=True, related_name='recipe', to='recipes.ShopList'),
        ),
    ]
