# Generated by Django 2.2.19 on 2021-05-13 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favorrecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favor'),
        ),
        migrations.AddField(
            model_name='shoprecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_recipe', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='shoprecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_recipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='shoprecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shop'),
        ),
    ]
