# Generated by Django 2.2.19 on 2021-05-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopList',
        ),
    ]
