# Generated by Django 2.2.19 on 2021-05-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210505_1855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
