# Generated by Django 2.2.19 on 2021-05-15 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_purchases'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopRecipe',
            new_name='Purchas',
        ),
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
