# Generated by Django 2.2.19 on 2021-05-22 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20210515_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchas',
            new_name='Purchase',
        ),
    ]
