# Generated by Django 2.2.19 on 2021-05-22 17:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210522_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorrecipe',
            options={'verbose_name': 'Избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Связь ингредиента и рецепта', 'verbose_name_plural': 'Связи ингредиентов и рецептов'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Рецепт в корзине покупок', 'verbose_name_plural': 'Рецепты в корзине покупок'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_shop',
        ),
        migrations.AlterField(
            model_name='favorrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favor_recipe', to='recipes.Recipe', verbose_name='Рецепт у избранного пользователя'),
        ),
        migrations.AlterField(
            model_name='favorrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favor_recipe', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь избранного рецепта'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='idol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL, verbose_name='На кого подписан пользователь'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient', verbose_name='ингредиент для рецепта'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe', verbose_name='рецепт для ингредиента'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_recipe', to='recipes.Recipe', verbose_name='Рецепт в корзине пользователя'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_recipe', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин корзины покупок'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag_brekfast',
            field=models.BooleanField(default=False, verbose_name='Завтрак'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag_dinner',
            field=models.BooleanField(default=False, verbose_name='Ужин'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag_lanch',
            field=models.BooleanField(default=False, verbose_name='Обед'),
        ),
    ]
