# Generated by Django 2.2.19 on 2021-05-10 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_remove_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorrecipe',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='favor_recipe',
            field=models.ManyToManyField(related_name='favorite', through='recipes.FavorRecipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
