# Generated by Django 2.2.19 on 2021-05-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210526_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes/', verbose_name='Загрузить фото'),
            preserve_default=False,
        ),
    ]
