# Generated by Django 2.2.19 on 2021-05-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210512_2048'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorrecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorite_user_recipe'),
        ),
    ]
