# Generated by Django 2.2.19 on 2021-05-12 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210512_2053'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorrecipe',
            name='unique_favorite_user_recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='favor_recipe',
        ),
        migrations.AlterField(
            model_name='favorrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='favorrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
