# Generated by Django 2.2.19 on 2021-05-13 11:42

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210513_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
