# Generated by Django 2.2.19 on 2021-05-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210526_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default='', verbose_name='Время приготовления'),
        ),
    ]
