# Generated by Django 2.2.19 on 2021-05-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20210528_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag_brekfast',
            new_name='tag_breakfast',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag_lanch',
            new_name='tag_lunch',
        ),
    ]
